#name = input("Enter your name: ")
#phone_number = input("Enter your phone number: ")
#result =len(name)
#result = name.find('h')
#result = name.rfind("h")
#result =  name.capitalize()
#result =  name.upper()
#result = name.lower()
#result = name.isdigit()
#result =  name.isalpha()
#result = phone_number.count("-")
#result = phone_number.replace("-", "_")
#print(result)
print(help(str))   # hi mne sbh formuala ahen likhya; sbh string methods